databases:
  - name: myblogdb
    plan: free
    databaseName: yblogdb
    user: stivhc

services:
  - type: web
    plan: free
    name: myblogdb
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myblogdb.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myblogdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
